import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useProtectedData } from '../management/session/useProtectedData'
import { getLive } from './api'
import type { HourSlot } from './types'
import type { LiveLine, LiveSnapshot } from './liveTypes'
import './live-operations.css'

const fmt=(n:number|null|undefined,d=0)=>n==null?'—':n.toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d})
const categoryColor=(name:string)=>Array.from(name.toLowerCase()).reduce((n,c)=>(n*31+c.charCodeAt(0))%6,0)
const fill=(n:number|null)=>Math.max(0,Math.min(100,n??0))
const stamp=(s:string|null,zone='Europe/London')=>s?new Date(s).toLocaleString('en-GB',{timeZone:zone,day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'No submission'
function tone(n:number|null,t:LiveSnapshot['thresholds']){return n===null?'neutral':n<t.amber?'danger':n<t.green?'warning':'success'}
function Progress({value,tone:color='success',label}:{value:number|null;tone?:string;label:string}){return <div className={`lo-progress lo-${color}`} role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value===null?undefined:fill(value)} aria-valuetext={value===null?'Not available':`${fmt(value,1)}%`}><span style={{width:`${fill(value)}%`}}/></div>}
function Gauge({value,empty,thresholds}:{value:number|null;empty:string;thresholds:LiveSnapshot['thresholds']}){
 return <div className={`lo-gauge lo-${tone(value,thresholds)}`} role="img" aria-label={`Last-Hour OEE: ${value===null?empty:fmt(value,1)+'%'}; actual packs divided by expected packs`}>
  <svg viewBox="0 0 140 140" aria-hidden="true"><circle className="lo-track" cx="70" cy="70" r="58"/><circle className="lo-ring" cx="70" cy="70" r="58" pathLength="100" strokeDasharray={`${fill(value)} 100`} transform="rotate(-90 70 70)"/></svg>
  <div><strong>{value===null?'—':`${fmt(value,1)}%`}</strong><span>{value===null?empty:'Last-Hour OEE'}</span></div>
 </div>
}
export function Trend({hours}:{hours:HourSlot[]}){
 const max=Math.max(100,...hours.map(h=>h.line.output_vs_target_percent??0))
 return <figure className="lo-trend"><figcaption>Last eight completed hours</figcaption><svg viewBox="0 0 276 66" preserveAspectRatio="none" role="img" aria-label="Hourly achievement trend; gaps mean no comparable update">
 <line x1="8" x2="272" y1={62-100/max*52} y2={62-100/max*52} className="lo-trend-target"/>
 {hours.map((h,i)=>{const value=h.line.output_vs_target_percent;const previous=hours[i-1]?.line.output_vs_target_percent;return <g key={h.hour_start}>
 {value!==null&&previous!=null&&<line x1={12+(i-1)*36} y1={62-previous/max*52} x2={12+i*36} y2={62-value/max*52} className="lo-trend-line"/>}
 {value!==null?<circle cx={12+i*36} cy={62-value/max*52} r="3" className="lo-trend-dot"><title>{h.hour_label}: {fmt(value,1)}%</title></circle>:<text x={12+i*36} y="58" textAnchor="middle">·</text>}
 </g>})}</svg><div className="lo-trend-labels">{hours.map(h=><span key={h.hour_start}>{new Date(h.hour_start).toLocaleTimeString('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit'})}</span>)}</div>
 <details><summary>Hourly values</summary><ul>{hours.map(h=><li key={h.hour_start}>{h.hour_label}: {h.line.output_vs_target_percent===null?(h.line.status==='not_scheduled'?'Not Scheduled':'No comparable update'):fmt(h.line.output_vs_target_percent,1)+'%'}</li>)}</ul></details></figure>
}
function LineCard({line,thresholds}:{line:LiveLine;thresholds:LiveSnapshot['thresholds']}){
 const h=line.last_hour;const v=h?.line.output_vs_target_percent??null;const expected=h?.line.target_packs??null;const actual=h?.line.actual_packs??null;const scale=Math.max(expected??0,actual??0,1)
 const empty=h?.line.status==='not_scheduled'?'Not Scheduled':h?.line.status==='no_reading'?'No update':h?.line.status==='idle'?'No scheduled record':'Not comparable'
 return <article className="lo-line" aria-label={`${line.name} performance`}><header><h2><span aria-hidden="true">▥</span> <Link to={`/dashboard?view=reports&line=${encodeURIComponent(line.name)}`}>{line.name}</Link></h2><span className={`lo-badge lo-${line.tone}`}>{line.status_label}</span></header>
 <p className="lo-product">{line.job?`${line.job.customer} · ${line.job.product}`:'No active product run'}</p>
 <p className="lo-muted">{line.job?`${fmt(line.job.pack_weight_kg,2)} kg · ${line.job.format??'Format not recorded'} · ${fmt(line.job.speed_ppm)} packs/min`:'Production state comes from recorded HMI events'}</p>
 <div className="lo-performance"><Gauge value={v} empty={empty} thresholds={thresholds}/><div className="lo-output"><p className="lo-muted">{h?.hour_label??'Last completed hour'}</p><dl><div><dt>Expected packs</dt><dd>{fmt(expected)}</dd></div><div><dt>Actual packs</dt><dd>{fmt(actual)}</dd></div></dl><div className="lo-compare" aria-label="Expected versus actual packs"><div className="lo-target" style={{width:`${(expected??0)/scale*100}%`}}/><div className={`lo-${tone(v,thresholds)}`} style={{width:`${(actual??0)/scale*100}%`}}/></div>{v!==null&&v>100&&<p className="lo-warning">Over target · review speed/counts</p>}{(h?.line.unaccounted_minutes??0)>0&&<p className="lo-warning">{fmt(h?.line.unaccounted_minutes,1)} min unaccounted</p>}</div></div>
 <Trend hours={line.trend}/><footer><span>Current job remaining <strong>{fmt(line.job?.remaining_pallets,2)} pallets</strong></span><span className="lo-muted">Last production<br/>{stamp(line.last_production_at)}</span></footer>
 </article>
}
export function LiveOperationsView({data,error,refresh,loading,now=Date.now(),week,onWeek}:{data:LiveSnapshot|null;error:string|null;refresh:()=>void;loading:boolean;now?:number;week:string;onWeek:(v:string)=>void}){
 const [inspection,setInspection]=useState<{line:string;category:string}|null>(null)
 const inspected=data?.breakdowns.find(l=>l.line===inspection?.line)?.breakdowns.find(c=>c.category===inspection?.category)
 const stale=!!data&&(now-new Date(data.generated_at).getTime()>90000||!!error)
 const categories=Array.from(new Set(data?.breakdowns.flatMap(l=>l.breakdowns.map(c=>c.category))??[])).sort()
 const largest=Math.max(1,...(data?.breakdowns.map(l=>l.unplanned_minutes)??[]))
 return <section className="lo"><header className="lo-header"><div><p className="lo-eyebrow">TONNAGEFLOW / PULSE</p><h1>Live Operations Dashboard</h1><p className="lo-muted">Live factory view · production, downtime and performance</p></div><div className="lo-header-meta"><time>{new Date(now).toLocaleString('en-GB',{timeZone:data?.timezone??'Europe/London',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><span>{data?.shift.label.replace(/^Day shift/,'Morning shift')??'Loading shift'} · {data?.lines.length??'—'} lines</span><button className="pd-button" onClick={refresh} disabled={loading}>{loading?'Refreshing...':'Refresh'}</button></div></header>
 <div className="lo-freshness"><span className={stale?'lo-warning':'lo-muted'}>{stale?'Stale snapshot · check connection':data?`Refreshed ${stamp(data.generated_at)}`:'Connecting...'}</span><span>HMI submissions, not machine telemetry · Latest submission: {stamp(data?.latest_submission_at??null)}</span><Link to="/dashboard?view=reports">Detailed production reports →</Link></div>
 {error&&<p role="alert" className="lo-alert">{error} {data?'Showing the last successful snapshot.':''}<button className="pd-button" onClick={refresh}>Retry</button></p>}
 {!data&&!error&&<p role="status">Loading recorded factory activity...</p>}
 {data&&<><section className="lo-week lo-panel" aria-label="Weekly production target"><div className="lo-week-title"><h2>{week?'Weekly Tonnage Target':'This Week’s Tonnage Target'}</h2><label>Week starting<input type="date" value={week||data.weekly.week_start} onChange={e=>onWeek(e.target.value)}/></label><button className="pd-button" onClick={()=>onWeek('')}>Current week</button><Link to={`/management/weekly-targets?week=${data.weekly.week_start}`}>Manage target →</Link></div><div className="lo-week-body"><div><strong>{fmt(data.weekly.actual_tonnes,1)}<small> / {fmt(data.weekly.target_tonnes,1)} tonnes</small></strong><p className="lo-muted">Confirmed production · {data.weekly.site} · {data.weekly.target_tonnes===null?'Target not set':data.weekly.window.label}</p></div><div className="lo-week-progress"><span>{data.weekly.progress_percent===null?'No comparable progress':`${fmt(data.weekly.progress_percent,1)}% of target`}</span><Progress value={data.weekly.progress_percent} label="Weekly target progress"/></div></div>{data.weekly.excluded_readings>0&&<p className="lo-warning">{data.weekly.excluded_readings} readings excluded: missing or invalid quantities/timing.</p>}<details><summary>Production basis and notes</summary>{data.weekly.notes && <p>{data.weekly.notes}</p>}{data.weekly.method}{data.weekly.boundary_readings>0&&` ${data.weekly.boundary_readings} whole readings cross the week boundary.`}</details></section>
 <div className="lo-kpis"><article className="lo-panel lo-kpi"><h2>Line status</h2><strong>{data.summary.status_counts.running??0} <small>Running at last report</small></strong><p>{data.summary.status_counts.changeover??0} Changeover · {data.summary.status_counts.stopped??0} Stopped</p><p className="lo-muted">{data.summary.status_counts.not_scheduled??0} Not Scheduled · {(data.summary.status_counts.idle??0)+(data.summary.status_counts.unknown??0)} Unconfirmed / idle</p></article><article className="lo-panel lo-kpi lo-danger"><h2>Ongoing faults</h2><strong>{data.summary.ongoing_faults}</strong><p>Unresolved production faults</p></article><article className="lo-panel lo-kpi lo-warning"><h2>Planned downtime today</h2><strong>{fmt(data.summary.planned_minutes,1)} <small>min</small></strong><p>{data.summary.planned_events} events · {fmt(data.summary.changeover_minutes,1)} min changeover included</p></article><article className="lo-panel lo-kpi lo-danger"><h2>Unplanned downtime today</h2><strong>{fmt(data.summary.unplanned_minutes,1)} <small>min</small></strong><p>{data.summary.unplanned_events} events · recorded stop time</p></article><article className="lo-panel lo-kpi lo-specialist"><h2>Average last-hour OEE</h2><strong>{fmt(data.summary.average_percent,1)}{data.summary.average_percent!==null?'%':''}</strong><p>{data.summary.eligible_lines}/{data.lines.length} eligible lines · weighted</p>{data.summary.previous_percent!==null&&data.summary.average_percent!==null&&<p>{fmt(data.summary.average_percent-data.summary.previous_percent,1)} pp vs previous hour</p>}<details><summary>Calculation</summary>{data.summary.average_method}</details></article></div>
 <div className="lo-lines">{data.lines.map(l=><LineCard key={l.name} line={l} thresholds={data.thresholds}/>)}</div>
 <p className="lo-method">OEE here means output achievement: actual packs ÷ expected packs × 100, including scheduled stop time. Not Availability × Performance × Quality. Red &lt;{data.thresholds.amber}% · Amber &lt;{data.thresholds.green}% · Green ≥{data.thresholds.green}%.</p>
 <div className="lo-lower"><section className="lo-panel"><h2>Top Ongoing Issues Right Now</h2>{!data.issues.length?<p className="lo-good-state">✓ No ongoing production or Engineering issues recorded</p>:<ol className="lo-issues">{data.issues.map(f=><li key={f.id}><Link to={`/dashboard/engineering?line=${encodeURIComponent(f.line)}&fault=${f.id}`}><strong>{f.line} · {f.machine}</strong><span>{f.reason}</span></Link><p><b>{fmt(f.open_minutes)} min</b> since opened · {f.production_stopped?'Production stopped':'Production restored'}</p><p className="lo-muted">{f.engineering_status} · {f.engineer??'Unassigned'} · {stamp(f.opened_at)}</p></li>)}</ol>}</section>
 <section className="lo-panel"><h2>Top Breakdowns by Line</h2><p className="lo-muted">Last seven days · recorded unplanned minutes</p><div className="lo-breakdowns">{data.breakdowns.map(l=><div key={l.line}><div className="lo-bar-label"><Link to={`/dashboard/engineering?line=${encodeURIComponent(l.line)}`}>{l.line}</Link><strong>{fmt(l.unplanned_minutes,1)} min</strong></div><div className="lo-stacked">{l.breakdowns.map(c=><button type="button" key={c.category} className={`lo-category-${categoryColor(c.category)}`} style={{width:`${c.minutes/largest*100}%`}} title={`${c.category}: ${fmt(c.minutes,1)} minutes, ${c.events} events`} aria-label={`${l.line}, ${c.category}: ${fmt(c.minutes,1)} minutes, ${c.events} events`} onClick={()=>setInspection({line:l.line,category:c.category})}/>)}</div></div>)}</div><div className="lo-legend">{categories.length?categories.map(c=><span key={c}><i className={`lo-category-${categoryColor(c)}`}/>{c}</span>):<span>No unplanned downtime recorded</span>}</div>{inspection&&inspected&&<div className="lo-inspection" role="region" aria-label="Breakdown records"><h3>{inspection.line} · {inspection.category}</h3><button className="pd-button" onClick={()=>setInspection(null)}>Close records</button><ul>{inspected.records.map(r=><li key={`${r.source}:${r.id}`}>{r.machine}: {r.reason} · {fmt(r.minutes,1)} min</li>)}</ul></div>}<details><summary>Timing and overlap rules</summary>{data.breakdown_method}</details></section>
 <section className="lo-panel"><h2>Changeover Readiness</h2>{data.lines.map(l=><div className="lo-readiness" key={l.name}><div className="lo-bar-label"><Link to={l.changeover?'/dashboard/qa':`/management/active-runs`}>{l.name}</Link><strong>{l.changeover?`${l.changeover.kind} · ${fmt(l.changeover.elapsed_minutes)} min`:l.job?`${fmt(l.job.remaining_pallets,2)} pallets`:'No active job'}</strong></div>{l.changeover?<p className="lo-muted">{l.changeover.physical_complete?'Physical work complete':'Physical work pending'} · QA {l.changeover.qa_status.replaceAll('_',' ')} · {l.changeover.engineering_ready?'Engineering ready':l.changeover.engineer??'Engineering not confirmed'}</p>:<><Progress value={l.job?.progress_percent??null} label={`${l.name} current job progress`}/><p className="lo-muted">Pallets remaining on current job · {l.job?.estimate_status??'Estimate unavailable'}</p></>}</div>)}</section></div>
 </>}
 </section>
}
export function LiveOperations(){
 const [week,setWeek]=useState('');const [now,setNow]=useState(Date.now())
 const report=useProtectedData((token,signal)=>getLive(token,week||null,signal),`live:${week}`)
 const {isLoading,loadedAt,error,reload}=report
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[])
 useEffect(()=>{if(isLoading)return;const timer=window.setTimeout(()=>{if(document.visibilityState==='visible')reload()},30000);return()=>window.clearTimeout(timer)},[isLoading,loadedAt,error,reload])
 useEffect(()=>{const resume=()=>{if(document.visibilityState==='visible')reload()};window.addEventListener('online',resume);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('online',resume);document.removeEventListener('visibilitychange',resume)}},[reload])
 return <LiveOperationsView data={report.data} error={report.error} loading={report.isLoading} refresh={report.reload} now={now} week={week} onWeek={setWeek}/>
}
