-- ==========================================================
-- TONNAGEFLOW PULSE
-- Migration 0001: Management area
-- ==========================================================
--
-- Adds four new tables for the Management area (production_lines,
-- machines, buttons, management_audit_log). Purely additive - no
-- existing table (production_runs, hourly_updates, downtime_events,
-- engineering_updates) is altered in any way.
--
-- NOT applied automatically by any script in this repo. Review this
-- file, then apply it (e.g. via the Supabase migration tool) once
-- approved.

BEGIN;

CREATE TABLE public.production_lines (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text NOT NULL UNIQUE,
    active          boolean NOT NULL DEFAULT true,
    display_order   integer NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.machines (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_line_id  bigint NOT NULL REFERENCES public.production_lines (id),
    name                text NOT NULL,
    active              boolean NOT NULL DEFAULT true,
    display_order       integer NOT NULL DEFAULT 0,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_machine_name_per_line UNIQUE (production_line_id, name)
);

CREATE INDEX idx_machines_production_line_id
    ON public.machines USING btree (production_line_id);

CREATE TABLE public.buttons (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id      bigint NOT NULL REFERENCES public.machines (id),
    name            text NOT NULL,
    event_type      text NOT NULL,
    ownership       text NOT NULL,
    fault_category  text NULL,
    display_order   integer NOT NULL DEFAULT 0,
    active          boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_button_event_type
        CHECK (event_type IN ('planned_downtime', 'unplanned_fault')),
    CONSTRAINT chk_button_ownership
        CHECK (ownership IN ('Production', 'Engineering'))
);

CREATE INDEX idx_buttons_machine_id
    ON public.buttons USING btree (machine_id);

CREATE TABLE public.management_audit_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action          text NOT NULL,
    manager_name    text NOT NULL,
    record_type     text NOT NULL,
    record_id       text NULL,
    previous_value  jsonb NULL,
    new_value       jsonb NULL,
    reason          text NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_management_audit_log_created_at
    ON public.management_audit_log USING btree (created_at DESC);

CREATE INDEX idx_management_audit_log_record
    ON public.management_audit_log USING btree (record_type, record_id);

-- Seed the three existing real production lines so Management has
-- something to configure immediately. Spelling matches
-- src/main.py's line_technicians_by_line / pack_sizes_by_line exactly.
INSERT INTO public.production_lines (name, display_order) VALUES
    ('Rovema', 1),
    ('GIC', 2),
    ('Guill', 3)
ON CONFLICT (name) DO NOTHING;

COMMIT;
